### ISSUE TITLE
Make VisibleGarrisonAllowedClasses optional

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/conditional_visible_garrisoning#3]
It should default to infantry+ranged when null.

`<VisibleGarrisonAllowedClasses datatype="tokens">Infantry+Ranged</VisibleGarrisonAllowedClasses>`

**Comment by LenaTheWolfess** [comment]
@StanleySweet  I guess you can close this one :)

done in https://github.com/0ADMods/conditional_visible_garrisoning/commit/aba8689445cadf7b0b7d6d36d87d5da2c6f1f69c
